version: '3'
services:
  mysql:
    container_name: cramstack-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: APIlerning
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  app:
    container_name: cramstack-API-APP
    restart: always
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql